kafka:
  user: ${KAFKA_USER}
  password: ${KAFKA_PSSWD}
  topic: K_TOPIC_0
  bootstrap-servers: adjusted-piranha-11234-us1-kafka.upstash.io:9092
#spring:
#  application:
#    name: kafka-stream
#  kafka:
#
#    properties:
#      security.protocol: SASL_SSL
#      sasl.mechanism: SCRAM-SHA-256
#      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${kafka.user}" password="${kafka.password}";
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.LongSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      transaction-id-prefix: tx-
server:
  port: 8069
  http2:
    enabled:
logging:
  pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"